services:
    Sourceability\Instrumentation\Profiler\TidewaysProfiler:
        class: 'Sourceability\Instrumentation\Profiler\TidewaysProfiler'
        tags:
            - { name: 'sourceability_instrumentation.profiler' }
