services:
    Sourceability\Instrumentation\Profiler\SymfonyProfiler:
        class: 'Sourceability\Instrumentation\Profiler\SymfonyProfiler'
        arguments:
            - '@?profiler'
            - '@?debug.stopwatch'
        tags:
            - { name: 'sourceability_instrumentation.profiler' }
